name: CI

on: 
  push:
    paths:
    - '**.js'
    

jobs:
  lint:
     
    runs-on: ubuntu-latest

    steps:
    - uses: "bltavares/actions/prettier@master"
    - name: prettier JavaScript file
    - with: 
        secrets: "GITHUB_TOKEN"
